export const ADDITION = 'ADDITION'
export const SUBSTRACTION = 'SUBSTRACTION'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const GET_DATA = 'GET_DATA'