export const Images = {
  blog_img: require('../images/blog.png'),
  parent_img: require('../images/Parent.png'),
  back_icon: require('../images/back.png'),
  close_icon: require('../images/close.png'),
  phone_icon: require('../images/phn.png'),
  map_icon: require('../images/Map1.png'),
  insta_icon: require('../images/insta.png'),
  fb_icon: require('../images/fb.png'),
  twitter_icon: require('../images/twitter.png'),
  linkIn_icon: require('../images/linkdin.png'),
  next_icon: require('../images/Next.png'),
  search_icon: require('../images/search.png'),
  search_img: require('../images/SearchPage.png'),
  filter_icon: require('../images/filter.png'),
  add_icon: require('../images/Add.png'),
  checked_img: require('../images/Checked.png'),
  unchecked_img: require('../images/square.png'),
  up_arrow: require('../images/up-arrow.png'),
  down_arrow: require('../images/drop-down.png'),
  visit_icon :   require('../images/Visiting.png'),
};
