export const Colors = {
  Primary: '#9561E2',
  Grey: '#93A4BF',
  DarkGrey: '#6D6D6D',
  Black: '#333333',
  Star: '#FFC109',
  White: '#FFF',
  BackGroundColor: '#F2F5FC',
};

export const Labels = {
  testimonials: 'Testimonials',
  about_Us: 'About Us',
  contact_Us: 'Contact us',
  faq: 'FAQs',
  filter: 'Filter',
  map: 'Find on Map',
  photo_gallery: 'Photo Gallery',
  event_details: 'Event Details',
  latest_Review: 'Latest Review',
  review: 'Review',
  search: 'Search',
  more: 'More',
  nursery: 'Nurseries',
  school: 'Schools',
  nannies: 'Nannies',
  compamy: 'Companies',
  tutor: 'Tutors',
};

export const Images = {
  blog_img: require('../assets/images/blog.png'),
  parent_img: require('../assets/images/Parent.png'),
  back_icon: require('../assets/images/back.png'),
  close_icon: require('../assets/images/close.png'),
  phone_icon: require('../assets/images/phn.png'),
  map_icon: require('../assets/images/Map1.png'),
  insta_icon: require('../assets/images/insta.png'),
  fb_icon: require('../assets/images/fb.png'),
  twitter_icon: require('../assets/images/twitter.png'),
  linkIn_icon: require('../assets/images/linkdin.png'),
  next_icon: require('../assets/images/Next.png'),
  search_icon: require('../assets/images/search.png'),
  search_img: require('../assets/images/SearchPage.png'),
  filter_icon: require('../assets/images/filter.png'),
  add_icon: require('../assets/images/Add.png'),
  checked_img: require('../assets/images/Checked.png'),
  unchecked_img: require('../assets/images/square.png'),
  up_arrow: require('../assets/images/up-arrow.png'),
  down_arrow: require('../assets/images/drop-down.png'),
  visit_icon: require('../assets/images/Visiting.png'),
};
